name: Deploy prod site on push

on: 
  push:
    branches: 
      - master
      
jobs:
  web-deploy:

    name: Deploy Angular App 🚀
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install NPM Modules
      run: npm install --force

    - name: Build Project ⛏
      run: npm run build
    
    - name: Sync Files 🚀
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
          username: root
          server: 102.219.179.152
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: ./dist/iheb-progect-soa # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/html/heart-of-carthage-dubai.com/src
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: 102.219.179.152
#         username: root
#         password: DxK17976L7Oq?
#         local-dir: ./dist/
#         server-dir: ./
#         dangerous-clean-slate: true
# name: Build and deploy
# on:
#   push:
#     branches: [master]
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build ⛏
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@main
#       - name: Install dependencies
#         run: npm i --force
#       - name: Build dependencies
#         run: npm run build
#       - name: Archive production artifact
#         uses: actions/upload-artifact@main
#         with:
#           name: dist
#           path: dist
#   deploy:
#     name: Deploy 🚀 - sabri
#     needs: build
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Checkout repository
#         uses: actions/checkout@main
#       - name: Download artifact
#         uses: actions/download-artifact@main
#         with: 
#           name: dist
#           path: dist
#       - name: Sync files to hosting
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with: 
#           server: 102.219.179.152
#           username: root
#           password: DxK17976L7Oq?
